### PR TITLE
Fix memory leaks

### LINKED ISSUE #53: Investigate huge memory usage
Users are reporting huge (27gb!) memory usage when loading folders and viewing them. This is insane, and whilst I don't get the same issue on my pc (only 700mb usage) I believe the AvaloniaUI TreeView is the issue as it doesn't virtualise the list items. This is confirmed in the memory profiler as all the newly-allocate ram is from Avalonia. [This performance page](https://docs.avaloniaui.net/docs/guides/development-guides/improving-performance) indicates switching to TreeDataGrid may help as it virtualises items.

### PR DESCRIPTION
**Pull request by LeftofZen**
Fixes #53

### CODE REVIEW

File: Core/DatFileParsing/SawyerStreamReader.cs [hunk 1]
```diff
@@ -153,9 +153,6 @@ public static (DatFileInfo DatFileInfo, ILocoObject? LocoObject) LoadFullObjectF
 
 			ValidateLocoStruct(s5Header, locoStruct, logger);
 
-			// add to object manager
-			SObjectManager.Add(newObj);
```
Comment (LeftofZen) [inline Core/DatFileParsing/SawyerStreamReader.cs:157]: this was the culprit
