### PR TITLE
fix off-by-one string table parse error

### LINKED ISSUE #35: Station Image Error
Hey LeftofZen, I've really been enjoying using your tool :-)

I found four station objects from Wisim-Welt that your tool cannot open the images.  Then when I clicked "export to directory" your tool exported the images of the next object up in the main list.  The status window at the bottom just displayed loading object... and saved images to...  no errors
Maybe it needs an error message when it can't find the images.  And it's a bug if it's exporting the wrong images.
Probably the objects are faulty too...  I don't have time tonight to load them up, and edit them into my trackst.dat file

I hope you can make some sense of this ;-)

[station files.zip](https://github.com/OpenLoco/ObjectEditor/files/14305607/station.files.zip)

### PR DESCRIPTION
**Pull request by LeftofZen**
Fixes #35

### CODE REVIEW

File: Core/DatFileParsing/SawyerStreamReader.cs [hunk 1]
```diff
@@ -154,50 +154,53 @@ public static (DatFileInfo DatFileInfo, ILocoObject? LocoObject) LoadFullObjectF
...
 
-				// add empty strings for every single language
-				foreach (var language in Enum.GetValues<LanguageId>())
-				{
-					languageDict.Add(language, string.Empty);
-				}
-
-				for (; ptr < data.Length && data[ptr] != 0xFF;)
+				// read string
+				for (; ptr < data.Length && data[ptr] != 0xFF; ++ptr)
```
Comment (LeftofZen) [inline Core/DatFileParsing/SawyerStreamReader.cs:193]: the issue was the missing `ptr++` which is what openloco does. in the old code, I was doing this addition inside my while loop, and then subtracting 1 afterwards to correct for the `\0` character. i just changes the code to work like openloco's string table parsing and who would have thought, it just works

File: Gui/MainFormModel.cs [hunk 2]
```diff
@@ -363,7 +363,7 @@ static void SerialiseHeaderIndexToFile(string filename, HeaderIndex headerIndex,
 			}
 			else
 			{
-				var obj = SawyerStreamReader.LoadFullObjectFromFile(filename);
+				var obj = SawyerStreamReader.LoadFullObjectFromFile(filename, logger: logger);
```
Comment (LeftofZen) [inline Gui/MainFormModel.cs:366]: this adds logging to the object loading

File: Core/Data/LanguageId.cs [hunk 3]
```diff
@@ -16,7 +16,7 @@ public enum LanguageId : uint8_t
 		chinese_traditional,
 		id_12,
 		portuguese,
-		blank = 254,
-		end = 255
+		//blank = 254,
```
Comment (LeftofZen) [inline Core/Data/LanguageId.cs:19]: these were not the cause of the bug, but they also just weren't necessary to include here

File: Core/Objects/TrainSignalObject.cs [hunk 4]
```diff
@@ -49,5 +50,16 @@ public ReadOnlySpan<byte> Save()
 			=> Mods
 			.SelectMany(mod => mod.Write().ToArray())
 			.ToArray();
+
+		public bool TryGetImageName(int id, out string? value)
+			=> ImageIdNameMap.TryGetValue(id, out value);
+
+		public static Dictionary<int, string> ImageIdNameMap = new()
```
Comment (LeftofZen) [inline Core/Objects/TrainSignalObject.cs:57]: unrelated to the issue, but i saw openloco had these so i added them
